# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzFhMzIxM2EzNjBmMWYxY2U2N2NkNDg0OTYxY2M3ZGEyZjkyYzE2ZDk1YmU0Nzg1NjUyNzEyN2Q4Y2U0YTc3ZTUwYjdiNGJmNWEyMzU4ZTc1NzZmNmU5MThlMGYxODY5NzQwYTQ2OTVjZjM3ZjliOTIyYWQyOGRkMWY2NTVhZWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
